### PR TITLE
Update Ruby to 3.3.1, and refresh github actions

### PR DESCRIPTION
**Pull request by huwd**
Resolves: https://github.com/govuk-one-login/tech-docs/issues/166

## Why

Spring cleaning and maintenance to ensure we're running reasonable versions.
The update to Ruby 3.3.x was delayed until they fixed a bug in 3.3.1.

Should now be unblocked on apple silicone.

## How to review

- @pauldougan could you switch to this branch and run `./preview-with-docker.sh` on a mac? Check there's no outstanding issues?

### CODE REVIEW

**Review by pauldougan — COMMENTED** [review]
I am using an intel based macbook using `2.6 GHz 6-Core Intel Core i7` and `macOS sonoma 14.5 (23F79)`

I can confirm that:
- `./preview-with-docker.sh` ran clean on the branch and i was able to manually test the tech docs site
- I was able to `rbenv install 3.3.1` followed by `bundle install`, `bundle exec middleman build` and `bundle exec middleman server` to run tech docs locally using a locally installed ruby

I cannot comment on the changes that relate to the github actions

**Comment by huwd** [comment]
confirmed works on mac. will merge tuesday

**Comment by huwd** [comment]
@pauldougan would you mind approving this so i can merge it?

**Review by pauldougan — APPROVED** [review]
tested locally and ran ok

**Pull request merged**
